// Generated by CoffeeScript 1.6.2
(function() {
  var Ewe, Group;

  Group = require("./group");

  Ewe = (function() {
    /*
    */
    function Ewe() {
      this._groups = {};
    }

    /*
     scope identifier used to clasify exactly what variants to use. Note 
     that many users might have the same scope - depending on what country
     they might live in, or other variables. Scope can also be specific to a user
     ID
    */


    Ewe.prototype.group = function(key) {
      return this._groups[key] || (this._groups[key] = new Group(key, this));
    };

    return Ewe;

  })();

  module.exports = function() {
    return new Ewe();
  };

}).call(this);
