// Generated by CoffeeScript 1.6.2
(function() {
  var Scope, Test, utils;

  Test = require("./test");

  utils = require("./utils");

  /*
   scope can be a users id, location, or anything that 
   could categorize a group of people.
  */


  Scope = (function() {
    /*
    */
    function Scope(key, ewe) {
      this.key = key;
      this.ewe = ewe;
      this._tests = {};
    }

    /*
     returns a test
    */


    Scope.prototype.test = function(name) {
      return this._tests[name] || (this._tests[name] = new Test(name, this));
    };

    return Scope;

  })();

  module.exports = Scope;

}).call(this);
