// Generated by CoffeeScript 1.6.2
(function() {
  var Test, utils;

  utils = require("./utils");

  Test = (function() {
    /*
    */
    function Test(name, scope) {
      this.name = name;
      this.scope = scope;
      this.ewe = scope.ewe;
      this._variants = [];
    }

    /*
     selects a variant
    */


    Test.prototype.select = function() {
      var variant, variantIndex;

      variantIndex = utils.getRandomIndex(this.scope.key + this.name, this._variants.length, this.weights());
      variant = this._variants[variantIndex];
      return variant;
    };

    /*
     returns the weights of the variants
    */


    Test.prototype.weights = function() {
      var variant, weights, _i, _len, _ref;

      weights = [];
      _ref = this._variants;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        variant = _ref[_i];
        weights.push(Math.max(variant.weight || 1, 1));
      }
      return weights;
    };

    /*
     sets the control variant
    */


    Test.prototype.control = function(name, options, value) {
      if (!arguments.length) {
        return this._control;
      }
      if (arguments.length === 2) {
        value = options;
        options = {};
      }
      options.control = true;
      this.variant(name, options, value);
      this._control = this._variants[this._variants.length - 1];
      return this;
    };

    /*
     creates a new variation
    */


    Test.prototype.variant = function(name, options, value) {
      if (arguments.length === 2) {
        value = options;
        options = {};
      }
      options.value = value;
      options.name = name;
      this._variants.push(options);
      return this;
    };

    /*
    */


    Test.prototype.start = function() {};

    /*
    */


    Test.prototype.complete = function() {};

    return Test;

  })();

  module.exports = Test;

}).call(this);
