// Generated by CoffeeScript 1.6.2
(function() {
  var Variation;

  Variation = (function() {
    /*
    */
    function Variation(options, test, group) {
      this.test = test;
      this.group = group;
      this.weight = options.weight;
      this.value = options.value;
    }

    return Variation;

  })();

  module.exports = Variation;

}).call(this);
